# Generated by Django 6.0.3 on 2026-04-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('new', 'Нові'), ('used', 'Вживані')], default='used', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.CharField(default='Київ', max_length=100),
        ),
    ]
