# Generated by Django 6.0.3 on 2026-04-14 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('make_id', models.IntegerField(primary_key=True, serialize=False)),
                ('make_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehiclemake'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.vehiclemake')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehiclemodel'),
        ),
    ]
