# Generated by Django 6.0.3 on 2026-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vehicletype_vehiclemodel_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електро'), ('hybrid', 'Гібрид'), ('gas', 'Газ')], default='petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Ручна / Механіка'), ('automatic', 'Автомат'), ('CVT', 'Варіатор'), ('DCT', 'Робот')], default='manual', max_length=20),
        ),
    ]
