# Generated by Django 6.0.4 on 2026-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_wallet_address_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='deal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'В очікуванні (Сплачено)'), ('completed', 'Завершено (Кошти вивільнено)'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], default='pending', max_length=20),
        ),
    ]
