# Generated by Django 6.0.4 on 2026-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_purchase_deal_id_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('active', 'Активне'), ('inactive', 'Неактивне'), ('pending', 'В очікуванні'), ('sold', 'Продано')], default='active', max_length=20),
        ),
    ]
